# Generated by Django 3.1.3 on 2021-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParcelle', models.CharField(max_length=100)),
                ('codePostal', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('surface', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
    ]
